project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-On Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-Class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html"
          - text: "In-Class Exercise 3"
            href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html"
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
          
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

      

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

