project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-On Excercise"
        menu:
          - text: "Hands-on Excercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-Class Excercise"
        menu:
          - text: "In-Class Excercise 1"
            href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
      
          
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

