---
title: "In-Class Excercise 5"
date: "`r Sys.Date()`"
format: html
execute:
  message: false
  warning: false
editor: visual
---

# Getting Started

```{r}
# sfdep (gonna use for the take home excercise 2)
pacman::p_load(tidyverse, tmap, sf, sfdep) 
```

# Importing Data

```{r}
studyArea <- st_read(dsn="data",
                     layer="study_area") %>%
  st_transform(crs = 3829)
```

```{r}
# Use EPSG to find the projection of a country. For instance, Taiwan is EPSG:3829
stores <- st_read(dsn = "data",
                  layer = "stores") %>%
  st_transform(crs = 3829)
```

## Visualizing the sf layers

```{r}
tmap_mode("view")
tm_shape(NGA) +
  tm_dots(col="purple", size=0.05) + 
  tm_view(set.zoom.limits = c(5,8))
```

```{r}
tmap_mode("plot")
```

```{r}
tmap_mode("view")
tm_shape(geoNGA) +
  tm_dots(col="purple", size=0.05) + 
  tm_view(set.zoom.limits = c(5,8))
```

```{r}
tmap_mode("plot")
```

# Local Colocation Quotients (LCLQ)

```{r}
# This is required for Take Home Excercise 3
nb <- include_self(
  st_knn(st_geometry(stores),6))

wt <- st_kernel_weights(nb,
                        stores,
                        "gaussian",
                        adaptive = TRUE)

FamilyMart <- stores %>%
  filter(Name == "Family Mart")
A <- FamilyMart$Name

SevenEleven <- stores %>%
  filter(Name == "7-Eleven")
B <- SevenEleven$Name

# LCLQ is a datable. You dont have a unique identifier.
LCLQ <- local_colocation(A, B, nb, wt, 49)

# The cbind only works if your dont sort the results (LCLQ). 
LCLQ_stores <- cbind(stores, LCLQ)

```

```{r}
tmap_mode("view")
tm_shape(studyArea) + 
  tm_polygons() + 
  tm_shape(LCLQ_stores)+
    tm_dots(col = "X7.Eleven",
            size = 0.01,
            border.col = "black",
            border.lwd = 0.5) + 
  tm_view(set.zoom.limits = c(12,16))

```
